### ISSUE TITLE
Discussion about baselines for CodRep

### ISSUE THREAD

**Issue by mallamanis** [KTH/CodRep-competition#13]
Hi,
Thanks a lot for organizing this :) Hope that you don't mind the drive-by issue submission: I would like to suggest three additional, strong, but reasonable, baselines:

- Random prediction over the lines where after the replacement the code still parses;
- The line that is the most similar to the line being added (e.g. max % common tokens between the lines);
- The combination of the above.

The reason I am suggesting this, is that these baselines seem easy "hacks" to achieve reasonable performance without any machine learning.

**Comment by egor-bogomolov** [comment]
Sounds reasonable. For now I've implemented second one and halfway in implementing first/third (halfway means that it's implemented but works slowly and not debugged properly).
Second idea on it's own gives around 85% accuracy.

**Comment by chenzimin** [comment]
Hi all,
These baseline algorithms that I included in this competition are really "stupid". I did not include other baselines since I do not know how these would perform compared with your algorithms. The baseline algorithms should be easily beaten and easily understood. 

If, however, that everyone seems to be able to beat the proposed baseline algorithms. And the idea of "*The line that is the most similar to the line being added*" or "*the code still parses*", is commonly adopted. Then I would add the proposed baseline algorithms to the set of baseline algorithms in the competition.

**Comment by monperrus** [comment]
Very nice to see you here @mallamanis!

> Hope that you don't mind the drive-by issue submission

Oh no, that's great to have a lively issue tracker for discussing all sorts of things!

**Comment by mallamanis** [comment]
Hi all,
Thanks for your prompt responses :)

My rationale for suggesting those baselines was that filtering the lines where parsing fails would be a constraint that I would bake-in to any model to filter obvious false positives. The "most similar line" baseline would be the first "sanity check" to check if an ML model captures something beyond line similarity (such as context around each line) which seems a somewhat strong predictor.

**Comment by monperrus** [comment]
> The "most similar line" baseline would be the first "sanity check" to check if an ML model captures something beyond line similarity (such as context around each line) which seems a somewhat strong predictor.

100% agree.

The corollary is that this dataset and loss function helps to see what ML techniques are good at capturing line similarity.

**Comment by mallamanis** [comment]
Agreed, although I am sure that capturing some information about the context will also useful.

**Comment by monperrus** [comment]
No more activity here, closing the issue. Don't hesitate to reopen if appropriate!
