### ISSUE TITLE
Compiler warning appended at the end of some files

### ISSUE THREAD

**Issue by mpatsis** [KTH/CodRep-competition#19]
I noticed that in some task files there is an extra line appended at the end of the file.
I think this this is probably a compiler warning that you appended by accident.
An example of this is 3.txt in Dataset 2. https://github.com/KTH/CodRep-competition/blob/master/Datasets/Dataset2/Tasks/3.txt

**Comment by chenzimin** [comment]
Thank you for noticing the error, I have identified the source of the error. It is due to `git diff`, which is used to compute the diff between two commits, it outputs `No newline at end of file` when there is no newline at the end of the file. 

So it is sure that these extra lines are not part of the task, I will just simply removed them from existing tasks. Thank you again for noticing the error.
