### ISSUE TITLE
"Hidden" dataset for weekly rankings without any solutions?

### ISSUE THREAD

**Issue by monperrus** [KTH/CodRep-competition#7]
Follow up of https://github.com/KTH/CodRep-competition/issues/6 (@EgorBu)

> I recommend using kaggle-style approach and publish test dataset without solutions, so you can receive predictions and publish public score and compute a private score.

**Comment by chenzimin** [comment]
Since we do not allow any evaluation of algorithms on "test" dataset, there is no need to publish them. The participant themselves can divide the dataset into training, testing and validation datasets. 

But if it is about more realistic weekly rankings (evaluation on datasets in this repo is more likely to overfit, therefore the ranking could be meaningless), then we could create another dataset for weekly rankings.

So this discussion should be about dataset used in weekly rankings, so I will change the title. And keep this issue open and see if anyone has an opinion on this.

**Comment by monperrus** [comment]
No more activity here, closing the issue. Don't hesitate to reopen if appropriate!
